name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

env:
  PROJECT_TYPE: KEXT

jobs:
  build:
    name: Build
    runs-on: macos-latest
    permissions:
      contents: write
    env:
      JOB_TYPE: BUILD
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: CI Bootstrap
        run: src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/ocbuild/master/ci-bootstrap.sh) && eval "$src" || exit 1
      - name: Lilu Bootstrap
        run: src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/Lilu/master/Lilu/Scripts/bootstrap.sh) && eval "$src" || exit 1
      - run: xcodebuild -configuration Debug -arch x86_64 build
      - run: xcodebuild -configuration Release -arch x86_64 build
      - name: Upload to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/*/*.zip
      - name: Upload build
        uses: svenstaro/upload-release-action@2.9.0
        if: github.event_name != 'pull_request'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/*/*.zip
          tag: ${{ github.event_name == 'release' && github.ref || 'nightly' }}
          body: ${{ github.event_name != 'release' && github.event.head_commit.message || '' }}
          file_glob: true
          prerelease: ${{ github.event_name != 'release' }}
          overwrite: true
