name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-11.0

    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: acidanthera/MacKernelSDK
          path: MacKernelSDK
      - name: Xcodebuild
        uses: sersoft-gmbh/xcodebuild-action@v1.1
        with:
          project: ThermalSolution.xcodeproj
          action: build
      - uses: actions/upload-artifact@v2
        with:
          name: ThermalSolution
          path: build/Release
